# Generated by Django 4.2.5 on 2023-09-26 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactus', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactus',
            old_name='name',
            new_name='firstName',
        ),
    ]
