# Generated by Django 4.2.5 on 2023-09-22 06:39

from django.db import migrations, models
import gallery.models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_remove_gallery_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='category',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='gallery',
            name='contentType',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='gallery',
            name='imageDescription',
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='gallery',
            name='imageTitle',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='gallery',
            name='originalname',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='gallery',
            name='path',
            field=models.ImageField(blank=True, null=True, upload_to=gallery.models.upload_path),
        ),
    ]
