# Generated by Django 4.2.5 on 2023-09-22 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_gallery_category_gallery_contenttype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='projectID',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
