# Generated by Django 4.2.5 on 2023-09-22 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_alter_gallery_projectid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='created_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='updated_By',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
