# Generated by Django 4.2.5 on 2023-09-22 08:39

from django.db import migrations, models
import gallery.models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_alter_gallery_created_by_alter_gallery_updated_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallery',
            old_name='path',
            new_name='imagePath',
        ),
        migrations.AddField(
            model_name='gallery',
            name='filePath',
            field=models.FileField(blank=True, null=True, upload_to=gallery.models.upload_path),
        ),
    ]
