# Generated by Django 4.2.5 on 2023-09-22 09:35

from django.db import migrations, models
import django.db.models.deletion
import gallery.models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0006_rename_path_gallery_imagepath_gallery_filepath'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='filePath',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='imagePath',
        ),
        migrations.CreateModel(
            name='FileGallery',
            fields=[
                ('gallery_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gallery.gallery')),
                ('filePath', models.FileField(blank=True, null=True, upload_to=gallery.models.upload_path)),
            ],
            bases=('gallery.gallery',),
        ),
        migrations.CreateModel(
            name='ImageGallery',
            fields=[
                ('gallery_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gallery.gallery')),
                ('imagePath', models.ImageField(blank=True, null=True, upload_to=gallery.models.upload_path)),
            ],
            bases=('gallery.gallery',),
        ),
    ]
