# Generated by Django 4.2.5 on 2023-09-22 10:26

from django.db import migrations, models
import gallery.models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0007_remove_gallery_filepath_remove_gallery_imagepath_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagegallery',
            name='gallery_ptr',
        ),
        migrations.AddField(
            model_name='gallery',
            name='path',
            field=models.FileField(blank=True, null=True, upload_to=gallery.models.upload_path),
        ),
        migrations.DeleteModel(
            name='FileGallery',
        ),
        migrations.DeleteModel(
            name='ImageGallery',
        ),
    ]
