# Generated by Django 4.2.5 on 2023-09-22 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0008_remove_imagegallery_gallery_ptr_gallery_path_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='projectID',
            field=models.CharField(max_length=100),
        ),
    ]
