# Generated by Django 4.2.5 on 2023-09-22 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0009_alter_gallery_projectid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='contentType',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='originalname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
