# Generated by Django 4.2.5 on 2023-09-19 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0005_alter_projects_percentvalue'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='aboutstitle',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='aboutussubtitle',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='imageDescription',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='updated_By',
            field=models.CharField(default='rama', max_length=50),
            preserve_default=False,
        ),
    ]
