# Generated by Django 4.2.5 on 2023-09-21 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0011_alter_specifications_specification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specifications',
            name='specification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='realestate.specification'),
        ),
    ]
