# Generated by Django 4.2.5 on 2023-09-21 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0012_alter_specifications_specification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specifications',
            name='specification',
        ),
        migrations.AddField(
            model_name='specifications',
            name='created_by',
            field=models.CharField(default=1000, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='specifications',
            name='feature',
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='specifications',
            name='title',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='specifications',
            name='updated_By',
            field=models.CharField(default='rama', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='specifications',
            name='projectID',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Specification',
        ),
    ]
