# Generated by Django 4.2.5 on 2023-09-26 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appNews', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appnews',
            old_name='imageId',
            new_name='imageIds',
        ),
        migrations.RenameField(
            model_name='appnews',
            old_name='imageUrl',
            new_name='imageUrls',
        ),
        migrations.RenameField(
            model_name='appnews',
            old_name='originalname',
            new_name='originalnames',
        ),
    ]
